// Defaul Tact error code for invalid owner
const ERROR_CODE_INVALID_OWNER: Int = 132;
// Jetton wallet balance doesn't have enough tokens
const ERROR_CODE_NOT_ENOUGH_BALANCE: Int = 6901;
// Need more TONs in request for fee
const ERROR_CODE_NEED_FEE: Int = 6902;
// Jetton already initialized
const ERROR_JETTON_INITIALIZED: Int = 6903;
// Jetton max supply exceeded
const ERROR_MAX_SUPPLY_EXCEEDED: Int = 6904;